# Docker compose schema version
version: "3.8"

services:
  app:
    container_name: docker-json-explorer-container
    image: json-explorer-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"